services:
  dev:
    build:
      context: .
      dockerfile: dockerfile_build/Dockerfile
    image: shudan-toko-maker-dev
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    volumes:
      - ./shudan-toko-maker:/app:cached
      - node_modules:/app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  node_modules:
